// Pin the timezone before any worker boots. Several components format dates for
// display, so without this the suite passes locally and fails on UTC CI (or the
// reverse) purely on the developer's machine settings.
process.env.TZ = 'UTC';

const nextJest = require('next/jest');

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',
});

const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testEnvironment: '<rootDir>/jest.environment.js',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    // The core is ESM-only: its exports map offers an `import` condition and
    // nothing else, which Jest's CommonJS resolver cannot follow. Point it
    // straight at the built entry points and let the transform below turn them
    // into CommonJS.
    '^vintasend-templates-management-dashboard-core/next$':
      '<rootDir>/node_modules/vintasend-templates-management-dashboard-core/dist/next/index.js',
    '^vintasend-templates-management-dashboard-core$':
      '<rootDir>/node_modules/vintasend-templates-management-dashboard-core/dist/index.js',
  },

  // The package is ESM, so it also has to be transformed. That is driven by
  // `transpilePackages` in next.config.ts, which next/jest reads when it builds
  // the transform ignore list; its own dependencies (openapi-fetch,
  // openapi-react-query) each publish a CommonJS build and resolve normally.
  testMatch: ['**/__tests__/**/*.test.{ts,tsx}'],

  // Radix dialogs, sheets and the debounced filter bars are slow to mount under
  // a loaded CI machine. The 5s default made whole suites flake even though
  // every assertion is deterministic.
  testTimeout: 20000,

  // Coverage is measured over the dashboard's own code. `components/ui/**` is
  // deliberately absent: those are shadcn primitives generated by
  // `npx shadcn add`, replaced wholesale on regeneration, and already covered
  // indirectly wherever the app renders them.
  collectCoverageFrom: [
    'app/**/*.{ts,tsx}',
    'lib/**/*.{ts,tsx}',
    'proxy.ts',
    // Type-only modules: they compile away to nothing, so istanbul reports them
    // as empty files and they only add noise to the report.
    '!lib/auth/types.ts',
    '!**/*.d.ts',
  ],
  coverageThreshold: {
    global: {
      statements: 85,
      branches: 72,
      functions: 75,
      lines: 85,
    },
  },
};

module.exports = createJestConfig(customJestConfig);
